// generated by stringer -type=Layout; DO NOT EDIT

package packer

import "fmt"

const _Layout_name = "LayoutByWidthLayoutByHeightLayoutByAreaLayoutByMax"

var _Layout_index = [...]uint8{0, 13, 27, 39, 50}

func (i Layout) String() string {
	if i < 0 || i >= Layout(len(_Layout_index)-1) {
		return fmt.Sprintf("Layout(%d)", i)
	}
	return _Layout_name[_Layout_index[i]:_Layout_index[i+1]]
}
